name : Test Commit

on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: EndBug/add-and-commit@v8
      with:
        default_author: github_actions
        message : "Updated latest push"

#     - uses: stefanzweifel/git-auto-commit-action@v4
#       with:
#         # Optional, but recommended
#         # Defaults to "Apply automatic changes"
#         commit_message: Automated Change
#     - uses: EndBug/add-and-commit@v7
#       with:
#         message: Show GitHub Actions logo
#         committer_name: GitHub Actions
#         committer_email: actions@github.com
        
#     - uses: actions/checkout@v2
#     - uses: EndBug/add-and-commit@v8
#         with:
#           default_author: github_actions
#           message : Updated latest push
